---
- hosts: webservers
  remote_user: root

  tasks:
    - include_tasks: ./plays/install-apache.yml
    - include_tasks: ./plays/configure-apache.yml

  handlers:
    - name: restart apache2
      service: name=apache2 state=restarted
